# Generated by Django 4.0.3 on 2022-04-15 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Geoinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_type', models.CharField(max_length=200)),
                ('_id', models.IntegerField()),
                ('key', models.BooleanField(null=True)),
                ('name', models.CharField(max_length=200)),
                ('iata_airport_code', models.BooleanField(null=True)),
                ('type', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('location_id', models.IntegerField(null=True)),
                ('inEurope', models.BooleanField()),
                ('countryCode', models.CharField(max_length=10)),
                ('coreCountry', models.BooleanField()),
                ('distance', models.BooleanField(null=True)),
                ('geo_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serwis2.geoposition')),
            ],
        ),
    ]
