# Generated by Django 4.0.3 on 2022-04-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serwis2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geoinfo',
            name='coreCountry',
        ),
        migrations.RemoveField(
            model_name='geoinfo',
            name='country',
        ),
        migrations.RemoveField(
            model_name='geoinfo',
            name='countryCode',
        ),
        migrations.RemoveField(
            model_name='geoinfo',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='geoinfo',
            name='geo_position',
        ),
        migrations.RemoveField(
            model_name='geoinfo',
            name='iata_airport_code',
        ),
        migrations.RemoveField(
            model_name='geoinfo',
            name='inEurope',
        ),
        migrations.RemoveField(
            model_name='geoinfo',
            name='key',
        ),
        migrations.RemoveField(
            model_name='geoinfo',
            name='location_id',
        ),
        migrations.AddField(
            model_name='geoinfo',
            name='latitude',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='geoinfo',
            name='longitude',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='GeoPosition',
        ),
    ]
